<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    '\Rappi\Ecommerce' => __DIR__ . '/src/Ecommerce.php',
    '\Rappi\Data\Data' => __DIR__ . '/src/Data/Data.php',
    '\Rappi\Data\Discount' => __DIR__ . '/src/Data/Discount.php',
    '\Rappi\Data\File' => __DIR__ . '/src/Data/File.php',
    '\Rappi\Data\Inventory' => __DIR__ . '/src/Data/Inventory.php',
    '\Rappi\Data\Product' => __DIR__ . '/src/Data/Product.php',
    '\Rappi\Data\Stock' => __DIR__ . '/src/Data/Stock.php',
    '\Rappi\Data\Store' => __DIR__ . '/src/Data/Store.php',
    '\Rappi\Data\Variation' => __DIR__ . '/src/Data/Variation.php',
    '\Rappi\Data\VariationStock' => __DIR__ . '/src/Data/VariationStock.php'
);